services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p $PORT core.asgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false

  - type: worker
    name: celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A core.celery worker --loglevel=info"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false

  - type: worker
    name: celery-beat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A core.celery beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false