# Generated by Django 5.2.5 on 2025-08-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('question', 'Question'), ('advice', 'Advice'), ('discussion', 'Discussion'), ('experience', 'Experience Sharing'), ('problem', 'Problem'), ('solution', 'Solution'), ('general', 'General')], max_length=50),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='category',
            field=models.CharField(choices=[('tips', 'Farming Tips'), ('market_trends', 'Market Trends'), ('seasonal_advice', 'Seasonal Advice'), ('pest_control', 'Pest Control'), ('weather', 'Weather Updates'), ('technology', 'Agricultural Technology'), ('success_stories', 'Success Stories')], max_length=50),
        ),
    ]
