# Generated by Django 5.2.5 on 2025-08-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_communitypost_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('category', models.CharField(choices=[('tips', 'Farming Tips'), ('market_trends', 'Market Trends'), ('seasonal_advice', 'Seasonal Advice'), ('pest_control', 'Pest Control'), ('weather', 'Weather Updates'), ('technology', 'Agricultural Technology'), ('success_stories', 'Success Stories')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
